### ISSUE TITLE
shieldcortex-realtime plugin missing interceptor.js after v4 upgrade

### ISSUE THREAD

**Issue by jarvis-drakon** [Drakon-Systems-Ltd/ShieldCortex#15]
## Bug
After upgrading from v3.5.0 to v4.0.0 via `npm install -g`, the shieldcortex-realtime OpenClaw plugin fails to load:

```
shieldcortex-realtime failed to load: Error: Cannot find module './interceptor.js'
```

## Root Cause
`npm install -g` updates the package but doesn't re-run `shieldcortex openclaw install` to copy the new plugin files to `~/.openclaw/extensions/shieldcortex-realtime/`. The old plugin files reference modules that moved in v4.

## Fix
- Add a postinstall hook that detects an existing OpenClaw installation and auto-updates the plugin files
- Or at minimum, print a warning: 'Run `shieldcortex openclaw install` to update your OpenClaw plugin'

## Workaround
`shieldcortex openclaw install` copies the correct files.
